### ISSUE TITLE
renv::restore() throws errors

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/mal-effect-calculations#68]
renv::restore() gets stuck at the Rhdf5lib, perhaps due to permissions or somthing like that.
I was able to install the same library manually with:
BiocManager::install("rhdf5")

Similar issue might arise for omxr package which can be manually installed like:
install.packages("devtools")
devtools::install_github("gregmacfarlane/omxr")

**Comment by johpiip** [comment]
Let's test this together. This repo uses packages from CRAN, GitHub, and BioConductor, and two latter may have their own difficulties. `omxr` from GitHub relies on `rhdf5` from BioConductor which relies on something in CRAN, so it may need some iteration if it does not now how to work it out on its own.

**Comment by johpiip** [comment]
The previous error did not appear anymore. There was an error with `sf v1.0-12` which was solved by upgrading `sf` (#75). Now, I think everything works. Let's open a new issue if we have more problems.
